GH Actions

diff --git a/.github/workflows/new-pull-request.yaml b/.github/workflows/new-pull-request.yaml
--- a/.github/workflows/new-pull-request.yaml
+++ b/.github/workflows/new-pull-request.yaml
@@ -18,32 +18,30 @@ jobs:
       with:
         go-version: 1.x
 
-    - name: Find namespace.yaml file
-      id: find-file
+    - name: Find Namespace YAML
+      id: find-namespace-yaml
       run: |
-        echo $GITHUB_SHA
-        commitId=$(echo $GITHUB_SHA | cut -c1-7)
-        echo "Commit ID = " ${commitId}
-        git diff --name-only HEAD $commitId
-        git diff --name-only HEAD $GITHUB_SHA
-        # git diff --name-only HEAD $GITHUB_SHA | grep -E "namespace.yaml" > changed_files.txt
-        # cat changed_files.txt
-        # echo "::set-output name=files::$(cat changed_files.txt)"
+        namespace_file=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep "namespace.yaml")
+        echo "file : " $namespace_file
+        if [ -n "$namespace_file" ]; then
+          namespace=$(yq eval '.metadata.name' "$namespace_file")
+          echo "::set-output name=namespace_name::$namespace_name"
+        fi
 
-    - name: Extract namespace
-      id: extract-namespace
-      run: |
-        while IFS= read -r file; do
-          echo "File Name: $file"
-          if [[ $file -eq "namespace.yaml" ]]; then
-            namespace=$(yq eval '.metadata.namespace' "$file" 2>/dev/null)
-            if [[ -z "$namespace" ]]; then
-              echo "::error::Kubernetes namespace not found in namespace.yml"
-              exit 1
-            fi
-            echo "Namespace: $namespace"
-          fi
-        done
+    # - name: Extract namespace
+    #   id: extract-namespace
+    #   run: |
+    #     while IFS= read -r file; do
+    #       echo "File Name: $file"
+    #       if [[ $file -eq "namespace.yaml" ]]; then
+    #         namespace=$(yq eval '.metadata.namespace' "$file" 2>/dev/null)
+    #         if [[ -z "$namespace" ]]; then
+    #           echo "::error::Kubernetes namespace not found in namespace.yml"
+    #           exit 1
+    #         fi
+    #         echo "Namespace: $namespace"
+    #       fi
+    #     done
 
     # - name: Check Namespace YAML and Kubernetes Namespace
     #   run: |
